//Code no longer generated by AI but by Noah Ross


LocalSensor localSensor(DHTPIN, DHTTYPE);

void setup() {
  Serial.begin(9600);
  delay(2000);
  Serial.println("DHT Sensor Test with LED");

  localSensor.begin();
  localSensor.update(true);

  pinMode(LED_PIN, OUTPUT); // Initialize the LED pin as an output
  digitalWrite(LED_PIN, LOW);  // Make sure LED is off initially
}

void loop() {
  // Read temperature and humidity
  localSensor.getTemperature();
  localSensor.getHumidity();

  // Print the results to the serial monitor


  // Check temperature and control LED
  if (temperature >= TEMP_THRESHOLD) {
    digitalWrite(LED_PIN, HIGH); // Turn LED ON
    Serial.println("Temperature is above threshold! LED is ON.");
  } else {
    digitalWrite(LED_PIN, LOW);  // Turn LED OFF
    Serial.println("Temperature is below threshold! LED is OFF.");
  }

  delay(5000); // Wait 5 seconds before next reading
}
