
//Code generated by Gemini 2.0, 3/30/25
#include <DHT.h>

// LED pin
#define LED_PIN 13 // Connect LED to pin 13 (or any other digital pin)

// Temperature threshold
#define TEMP_THRESHOLD 25.0 // Temperature in Celsius

dht DHT();

void setup() {
  Serial.begin(9600);
  delay(2000);
  Serial.println("DHT Sensor Test with LED");
  //dht.begin();
  pinMode(LED_PIN, OUTPUT); // Initialize the LED pin as an output
  digitalWrite(LED_PIN, LOW);  // Make sure LED is off initially
}

void loop() {
  DHT.read22(2);
  // Read temperature and humidity
  float temperature = dht.readTemperature();
  float humidity = dht.readHumidity();

  // Check if any reads failed and exit early.
  if (isnan(humidity) || isnan(temperature)) {
    Serial.println(F("Failed to read from DHT sensor!"));
    delay(1000);
    return;
  }

  // Print the results to the serial monitor
  Serial.print("Humidity: ");
  Serial.print(humidity);
  Serial.print(" %\t");
  Serial.print("Temperature: ");
  Serial.print(temperature);
  Serial.println(" *C");
  delay(200);

  // Check temperature and control LED
  if (temperature >= TEMP_THRESHOLD) {
    digitalWrite(LED_PIN, HIGH); // Turn LED ON
    Serial.println("Temperature is above threshold! LED is ON.");
  } else {
    digitalWrite(LED_PIN, LOW);  // Turn LED OFF
    Serial.println("Temperature is below threshold! LED is OFF.");
  }

  delay(1800); // Wait 2 seconds before next reading
}
