#include <Arduino.h>
#include "LocalSensor.h"
//Code no longer generated by AI but by Noah Ross

#define DHTPIN 2
#define DHTTYPE DHT11

LocalSensor localSensor(DHTPIN, DHTTYPE);

void setup() {
  Serial.begin();
  delay(2000);
  Serial.println("DHT Sensor Test with LED");

  localSensor.begin();
  localSensor.update(true);

}

void loop() {
  // Read temperature and humidity
  double temperature = localSensor.getTemperature();
  double humidity = localSensor.getHumidity();

  // Print the results to the serial monitor


  //hard-code temp threshold for now
  double TEMP_THRESHOLD = 25.0;

  // Check temperature and control LED
  if (temperature >= TEMP_THRESHOLD) {
    Serial.println("Temperature is above threshold!");
  } else {
    Serial.println("Temperature is below threshold!");
  }

  delay(5000); // Wait 5 seconds before next reading
}