#include <Arduino.h>
#include "LocalSensor.h"
#include "Encoder.h"
//Code no longer generated by AI but by Noah Ross

#define DHTPIN 2
#define DHTTYPE DHT11
#define ENCODEPINCLK 4
#define ENCODEPINDT 5
#define ENCODEPINSW 6

LocalSensor localSensor(DHTPIN, DHTTYPE);
Encoder encoder(ENCODEPINCLK, ENCODEPINDT, ENCODEPINSW);

void setup() {
  Serial.begin(115200);
  delay(2000);
  Serial.println("DHT Sensor Test with LED");

  localSensor.begin();
  localSensor.update(true);

}

void loop() {
  int TEMP_THRESHOLD = encoder.selectTemperature();

  // Read temperature and humidity
  double temperature = localSensor.getTemperature();
  double humidity = localSensor.getHumidity();

    // Print the results to the serial monitor
  Serial.println(temperature);

  // Check temperature and control LED
  if (temperature >= TEMP_THRESHOLD) {
    Serial.println("Temperature is above threshold!");
  } else {
    Serial.println("Temperature is below threshold!");
  }

  delay(5000); // Wait 5 seconds before next reading
}
